# Hypothesis testing Exercise

### Q1)  A F&B manager wants to determine whether there is any
### significant difference in the diameter of the cutlet between two
### units. A randomly selected sample of cutlets was collected from
### both units and measured? Analyze the data and draw inferences
### at 5% significance level. Please state the assumptions and tests
### that you carried out to check validity of the assumptions.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
ls

 Volume in drive C is OS
 Volume Serial Number is 662D-09A6

 Directory of C:\Users\Vaibhav Kinge

09/18/2022  10:05    <DIR>          .
09/18/2022  10:05    <DIR>          ..
08/11/2022  13:18    <DIR>          .anaconda
08/11/2022  14:12    <DIR>          .conda
08/12/2022  16:49                42 .condarc
08/11/2022  13:12    <DIR>          .continuum
05/08/2019  22:59    <DIR>          .eclipse
09/17/2022  14:48    <DIR>          .ipynb_checkpoints
08/11/2022  09:14    <DIR>          .ipython
08/16/2022  13:51    <DIR>          .jupyter
11/22/2019  11:02    <DIR>          .m2
08/11/2022  09:18    <DIR>          .matplotlib
11/14/2021  15:02    <DIR>          .p2
08/12/2022  10:56    <DIR>          .spyder-py3
09/03/2022  11:15    <DIR>          .streamlit
05/08/2019  22:57    <DIR>          .tooling
02/08/2022  13:23    <DIR>          .vscode
06/25/2021  11:14    <DIR>          3D Objects
11/17/2021  22:12               563 acceptance_letter.txt
09/16/2022  14:57           170,988 

In [3]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_li

In [4]:
Cutlets = pd.read_csv('D:\Hypothesis CSV assignment\Cutlets.csv')

In [5]:
Cutlets

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

#### Hypothesis Formulation

H0: There is no significant difference in diameter of the cutlet between two units.# u1 = u2
Ha: There is a significant difference in diameter of the cutlet between two units.#u1 != u2 #### Level of signficance = 5%
##### 2 sample independent T test

In [6]:
t_val,p_val = stats.ttest_ind(a = Cutlets['Unit A'], b = Cutlets['Unit B'])
t_val,p_val

(0.7228688704678063, 0.4722394724599501)

In [7]:
p_val = p_val/2
p_val

0.23611973622997506

In [8]:
if p_val<0.05:
    print('we reject the null hypothesis and we can say that there is a significant difference in diameter of the cutlets between two units')
else:
    print('we do not reject the null hypothesis and we can say that there is no signficant difference in diameter of the cutlets between two units')

we do not reject the null hypothesis and we can say that there is no signficant difference in diameter of the cutlets between two units


### Q2) A hospital wants to determine whether there is any
### difference in the average Turn Around Time (TAT) of reports
### of the laboratories on their preferred list. They collected a
### random sample and recorded TAT for reports of 4
### laboratories. TAT is defined as sample collected to report
### dispatch.

### Analyze the data and determine whether there is any
### difference in average TAT among the different laboratories
### at 5% significance level.

In [9]:
LabTAT = pd.read_csv('D:\Hypothesis CSV assignment\LabTAT.csv')

In [10]:
LabTAT

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

#### Hypothesis Formulation:

H0: All the average TAT of reports of the laboratories are equal.
Ha: At least one average TAT of reports of laboratories is different.#### Level of significance = 5% #### We perform ANOVA Test.

In [11]:
statistics,p_val = stats.f_oneway(LabTAT['Laboratory 1'],LabTAT['Laboratory 2'],LabTAT['Laboratory 3'],LabTAT['Laboratory 4'])
statistics,p_val

(118.70421654401437, 2.1156708949992414e-57)

In [12]:
if p_val<0.05:
    print('We reject the null hypothesis and we can say that there is signficant difference in average TAT of reports of the laboratories.')
else:
    print('We do not reject the null hypothesis and we can say that there is no signficant difference in average TAT of reports of the laboratories.')

We reject the null hypothesis and we can say that there is signficant difference in average TAT of reports of the laboratories.


### Q3) Sales of products in four different regions is tabulated for males and females.
### Find if male-female buyer rations are similar across regions.



In [13]:
BuyerRatio = pd.read_csv('D:\Hypothesis CSV assignment\BuyerRatio.csv')

In [14]:
BuyerRatio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

#### Hypothesis Formulation

H0:All proportions are equal.
Ha: Not all proportion are equal. #### Level of signficance = 5% (Considered as 5% as level of signficance is not mentioned)
We perform Chi-squared Test

In [15]:
del BuyerRatio['Observed Values']

In [16]:
BuyerRatio

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [17]:
stats.chi2_contingency(observed = BuyerRatio)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [18]:
chi2_score,p_val,dof,expected = stats.chi2_contingency(observed = BuyerRatio)
print('***************************************************')
print('CHI-SQAURE TEST RESULTS')
print('CHI2 Value           :',chi2_score)
print('P-value              :',p_val)
print('Degree of Freedom    :',dof)
print('Expected Table       :\n',expected)
print('***************************************************')

***************************************************
CHI-SQAURE TEST RESULTS
CHI2 Value           : 1.595945538661058
P-value              : 0.6603094907091882
Degree of Freedom    : 3
Expected Table       :
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]
***************************************************


In [20]:
if p_val<0.05:
    print('We reject the null hypothesis and we can say that Not all proportion are equal.')
else:
    print('We do not reject the null hypothesis and we can say that all proportion are equal.')

We do not reject the null hypothesis and we can say that all proportion are equal.


### Q4) TeleCall uses 4 centers around the globe to process
### customer order forms. They audit a certain % of the
### customer order forms. Any error in order form
### renders it defective and has to be reworked before
### processing. The manager wants to check whether the
### defective % varies by centre. Please analyze the data
### at 5% significance level and help the manager draw
### appropriate inferences.

In [21]:
Customer = pd.read_csv('D:\Hypothesis CSV assignment\Costomer+OrderForm.csv')

In [22]:
Customer

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [24]:
Customer.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [25]:
Customer.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [26]:
Customer.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [27]:
Customer_values = pd.DataFrame({'Phillippines':[271,29],'Indonesia':[267,33],'Malta':[269,31],'India':[280,20]})
Customer_values

Phillippines  Indonesia  Malta  India
0           271        267    269    280
1            29         33     31     20

#### Hypothesis Formulation:

H0: The defective percentage does not varies significantly by centre.
Ha: The defective percentage does varies significantly by centre. ##### Level of signficance = 5% #### We perform Chi-squared Test.

In [28]:
stats.chi2_contingency(observed = Customer_values)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [29]:
chi2_score,p_val,dof,expected = stats.chi2_contingency(observed = Customer_values)
print('***************************************************')
print('CHI-SQAURE TEST RESULTS')
print('CHI2 Value           :',chi2_score)
print('P-value              :',p_val)
print('Degree of Freedom    :',dof)
print('Expected Table       :\n',expected)
print('***************************************************')

***************************************************
CHI-SQAURE TEST RESULTS
CHI2 Value           : 3.858960685820355
P-value              : 0.2771020991233135
Degree of Freedom    : 3
Expected Table       :
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]
***************************************************


In [30]:
if p_val<0.05:
    print('We reject the null hypothesis and we can say that the defective percentage does not varies significantly by centre.')
else:
    print('We do not reject the null hypothesis and we can say that the defective percentage does not varies significanly by centre.')

We do not reject the null hypothesis and we can say that the defective percentage does not varies significanly by centre.


=======================================================END=====================================================================